(function () {
  const state = { capabilities: null, dashboard: null, staticSamples: [], images: { custom: [], default: [] }, models: [], selectedImageId: null, selectedModelId: null };
  const $ = (selector) => document.querySelector(selector);
  const escapeHtml = (value) => String(value ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#39;");
  const formatNumber = (value, digits = 4) => Number.isFinite(Number(value)) ? Number(value).toFixed(digits) : "—";
  const setError = (target, message) => { const el = $(target); el.textContent = message || ""; el.classList.toggle("hidden", !message); };
  async function fetchJson(url, options) { let response; try { response = await fetch(url, options); } catch (_) { throw new Error("NETWORK_ERROR"); } const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.error || `HTTP_${response.status}`); return payload; }
  function friendlyError(error) { const message = String(error?.message || error); if (message.includes("MODEL_UNAVAILABLE")) return "Model đã chọn hiện không khả dụng."; if (message.includes("DEPENDENCY_MISSING")) return "Máy chủ Live Demo chưa có đầy đủ thành phần cần thiết để chạy mô hình."; if (message.includes("MODEL_LOAD_FAILED")) return "Không thể tải mô hình. Vui lòng thử lại sau."; if (message.includes("INVALID_IMAGE")) return "Không thể đọc hoặc xử lý ảnh. Vui lòng chọn PNG hoặc JPEG hợp lệ."; if (message.includes("FILE_TOO_LARGE") || message.includes("413")) return "Ảnh vượt quá dung lượng cho phép 10 MB."; if (message.includes("NETWORK_ERROR")) return "Không thể kết nối tới máy chủ. Vui lòng thử lại."; if (message.includes("STATIC_SAMPLE_UNAVAILABLE")) return "Không thể tải dữ liệu mẫu này."; return "Không thể hoàn tất phân đoạn cho ảnh này."; }
  function buildTable(columns, rows) { if (!rows.length) return '<p class="muted-note">Chưa có dữ liệu.</p>'; return `<div class="table-wrap"><table><thead><tr>${columns.map((c) => `<th>${escapeHtml(c.label)}</th>`).join("")}</tr></thead><tbody>${rows.map((row) => `<tr>${columns.map((c) => `<td>${escapeHtml(c.render ? c.render(row) : row[c.key])}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`; }
  function renderDashboard() { const datasets = state.dashboard?.overview?.datasets || []; $("#research-disclaimer").textContent = state.dashboard?.disclaimer || ""; $("#dataset-table").innerHTML = buildTable([{ label: "Bộ dữ liệu", key: "name" }, { label: "Tổng", key: "total" }, { label: "Dương tính", key: "positive" }, { label: "Âm tính", key: "negative" }, { label: "Train", key: "train" }, { label: "Val", key: "validation" }, { label: "Test", key: "test" }], datasets); const e = state.dashboard?.experiments || {}; const c = [{ label: "Model", key: "model", render: (r) => r.model || r.method }, { label: "Dice ↑", key: "dice", render: (r) => formatNumber(r.dice, 3) }, { label: "IoU ↑", key: "iou", render: (r) => formatNumber(r.iou, 3) }, { label: "HD95 ↓", key: "hd95", render: (r) => formatNumber(r.hd95, 3) }]; $("#btxrd-backbones-table").innerHTML = buildTable(c, e.btxrd_backbones || []); $("#btxrd-ablation-table").innerHTML = buildTable(c, e.btxrd_ablation || []); $("#fracatlas-backbones-table").innerHTML = buildTable(c, e.fracatlas_backbones || []); $("#fracatlas-ablation-table").innerHTML = buildTable(c, e.fracatlas_ablation || []); }
  const normalizeStatic = (p) => ({ source: "static", displayName: p.model?.display_name || "Prepared static result", modelName: p.model?.display_name || "", artifacts: p.artifacts || {}, uncertainty: p.uncertainty || {}, referenceMetrics: p.reference_metrics || {}, note: "Kết quả được chuẩn bị offline từ pipeline nghiên cứu đã đăng ký.", provenance: p.provenance || {} });
  const normalizeLive = (p) => ({ source: "live", displayName: p.display_name || p.model_id, modelName: p.display_name || "", artifacts: { original: p.original_image_url, overlay: p.overlay_image_url, mask: p.mask_image_url, probability: p.uncertainty?.tumor_probability?.heatmap_url, entropy: p.uncertainty?.pixel_entropy?.heatmap_url }, uncertainty: p.uncertainty || {}, referenceMetrics: { available: false }, note: p.note || "Kết quả inference từ backend.", provenance: {} });
  function renderGallery(result) { const cards = [["Ảnh gốc", result.artifacts.original, "Ảnh X-quang gốc"], ["Segmentation overlay", result.artifacts.overlay, "Kết quả segmentation overlay"], ["Predicted mask", result.artifacts.mask, "Mask phân đoạn dự đoán"], ["Tumor probability", result.artifacts.probability, "Heatmap xác suất vùng tổn thương"], ["Predictive entropy", result.artifacts.entropy, "Heatmap predictive entropy"]].filter(([, url]) => Boolean(url)); $("#result-gallery").innerHTML = cards.map(([label, url, alt]) => `<figure class="image-panel"><figcaption>${escapeHtml(label)}</figcaption><div class="image-frame ${label !== "Ảnh gốc" ? "result-frame" : ""}"><img src="${escapeHtml(url)}" alt="${escapeHtml(alt)}" /></div>${label.includes("entropy") ? '<div class="heatmap-legend"><span>Thấp</span><i></i><span>Cao</span></div>' : ""}</figure>`).join(""); }
  function renderUncertainty(u) { const entropy = Boolean(u.pixel_entropy?.available); $("#uncertainty-panel").classList.toggle("hidden", !entropy && !u.global && !u.boundary); if (!entropy && !u.global && !u.boundary) return; $("#uncertainty-note").textContent = u.note || "Các chỉ số là hậu kiểm mô hình, không phải độ chắc chắn chẩn đoán."; const global = u.global || {}, boundary = u.boundary || {}, summary = u.summary || {}; const cards = [["H_G · global predictive entropy", global.available ? formatNumber(global.value) : "—", global.available ? "Trung bình entropy nhị phân chuẩn hóa." : "Không có scalar entropy được lưu cùng artifact này."], ["H_B · boundary entropy", boundary.available ? formatNumber(boundary.value) : "—", boundary.available ? "Entropy trung bình trên biên dự đoán." : "Không áp dụng cho model hoặc artifact này."], ["Uncertain pixel ratio", entropy ? formatNumber(summary.uncertain_pixel_ratio) : "—", "Tỷ lệ pixel vượt ngưỡng analysis của mô hình."]]; $("#uncertainty-score-grid").innerHTML = cards.map(([label, value, detail]) => `<article class="score-card"><p class="metric-label">${escapeHtml(label)}</p><p class="metric-value small">${escapeHtml(value)}</p><p class="score-detail">${escapeHtml(detail)}</p></article>`).join(""); const url = u.pixel_entropy?.heatmap_url; $("#uncertainty-heatmaps").innerHTML = url ? `<figure class="image-panel compact heatmap-panel"><figcaption>Predictive entropy map</figcaption><div class="image-frame result-frame"><img src="${escapeHtml(url)}" alt="Predictive entropy map" /></div><p class="score-detail">Entropy nhị phân chuẩn hóa: thấp → cao.</p><div class="heatmap-legend"><span>Thấp</span><i></i><span>Cao</span></div></figure>` : ""; const risk = u.risk_control || {}; $("#risk-control-note").textContent = risk.note || ""; $("#risk-control-status").innerHTML = `<article class="availability-note ${risk.available ? "available" : "unavailable"}"><strong>${risk.available ? "CRC/conformal artifact sẵn sàng" : "Không áp dụng cho checkpoint hiện tại"}</strong><p>${risk.available ? "Risk-control output được cung cấp bởi artifact checkpoint-specific." : "Web không tạo CRC/risk-control metadata thay thế."}</p></article>`; }
  function renderReferenceMetrics(m) { const available = Boolean(m?.available); $("#reference-metrics").classList.toggle("hidden", !available); if (!available) return; $("#reference-metrics-grid").innerHTML = [["Dice", m.dice], ["IoU", m.iou], ["HD95", m.hd95], ["Precision", m.precision], ["Recall", m.recall]].map(([l, v]) => `<article class="score-card"><p class="metric-label">${l}</p><p class="metric-value small">${formatNumber(v)}</p></article>`).join(""); }
  function renderResult(r) { $("#stage-source").textContent = r.source === "static" ? "Prepared static result" : "Live inference output"; $("#stage-title").textContent = r.displayName; $("#stage-summary").textContent = r.note; $("#stage-badges").innerHTML = [r.source === "static" ? "precomputed" : "live", r.modelName, r.provenance?.split ? `split:${r.provenance.split}` : null].filter(Boolean).map((v) => `<span class="pill">${escapeHtml(v)}</span>`).join(""); renderGallery(r); renderUncertainty(r.uncertainty); renderReferenceMetrics(r.referenceMetrics); }
  async function loadStaticResult(id) { setError("#static-error", ""); try { renderResult(normalizeStatic(await fetchJson(`/static-samples/${encodeURIComponent(id)}`))); } catch (e) { setError("#static-error", friendlyError(e)); } }
  function renderStaticOptions() { const select = $("#static-sample-select"); select.innerHTML = state.staticSamples.filter((s) => s.available).map((s) => `<option value="${escapeHtml(s.id)}">${escapeHtml(s.display_name)}</option>`).join(""); if (select.options.length) loadStaticResult(select.options[0].value); }
  const flattenImages = () => [...(state.images.default || []), ...(state.images.custom || [])];
  function renderLiveOptions() { const models = state.models.filter((m) => m.available), images = flattenImages(), model = $("#model-select"), image = $("#image-select"); model.innerHTML = models.map((m) => `<option value="${escapeHtml(m.model_id)}">${escapeHtml(m.display_name)}</option>`).join("") || '<option value="">Không có model khả dụng</option>'; image.innerHTML = images.map((i) => `<option value="${escapeHtml(i.id)}">${escapeHtml(i.display_name || i.filename)}</option>`).join(""); state.selectedModelId = model.value || null; state.selectedImageId = image.value || null; $("#live-preview").src = images.find((item) => item.id === state.selectedImageId)?.image_url || ""; $("#run-live-segmentation").disabled = !state.selectedModelId || !state.selectedImageId; }
  async function ensureLiveData() { const [models, images] = await Promise.all([fetchJson("/models"), fetchJson("/get_images")]); state.models = models.models || []; state.images = images || { custom: [], default: [] }; renderLiveOptions(); }
  function setDemoMode(mode) { if (mode === "live" && !state.capabilities?.features?.live_demo) return; $("#static-demo-panel").classList.toggle("hidden", mode !== "static"); $("#live-demo-panel").classList.toggle("hidden", mode !== "live"); ["static", "live"].forEach((name) => { const tab = $(`#${name}-tab`); const active = name === mode; tab.classList.toggle("is-active", active); tab.setAttribute("aria-selected", String(active)); }); if (mode === "live") ensureLiveData().catch((e) => setError("#live-error", friendlyError(e))); }
  async function uploadImage() { const [file] = $("#live-upload").files || []; if (!file) return; if (file.size > 10 * 1024 * 1024) return setError("#live-error", "Ảnh vượt quá dung lượng cho phép 10 MB."); const form = new FormData(); form.append("images", file); setError("#live-error", ""); try { const uploaded = await fetchJson("/upload_images", { method: "POST", body: form }); const images = await fetchJson("/get_images"); state.images = images; renderLiveOptions(); $("#image-select").value = uploaded[0]?.id || $("#image-select").value; state.selectedImageId = $("#image-select").value; } catch (e) { setError("#live-error", friendlyError(e)); } }
  async function runLiveSegmentation() { if (!state.selectedImageId || !state.selectedModelId) return; const button = $("#run-live-segmentation"); button.disabled = true; button.textContent = "Đang phân đoạn và tính bất định..."; setError("#live-error", ""); try { renderResult(normalizeLive(await fetchJson("/segment", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ image_id: state.selectedImageId, model_id: state.selectedModelId }) }))); } catch (e) { setError("#live-error", friendlyError(e)); } finally { button.disabled = false; button.textContent = "Chạy phân đoạn"; } }
  function bindEvents() { $("#static-tab").addEventListener("click", () => setDemoMode("static")); $("#live-tab").addEventListener("click", () => setDemoMode("live")); $("#static-sample-select").addEventListener("change", (e) => loadStaticResult(e.target.value)); $("#model-select").addEventListener("change", (e) => { state.selectedModelId = e.target.value; }); $("#image-select").addEventListener("change", (e) => { state.selectedImageId = e.target.value; $("#live-preview").src = flattenImages().find((item) => item.id === state.selectedImageId)?.image_url || ""; }); $("#live-upload").addEventListener("change", uploadImage); $("#run-live-segmentation").addEventListener("click", runLiveSegmentation); }
  async function bootstrap() { bindEvents(); try { const [capabilities, dashboard] = await Promise.all([fetchJson("/capabilities"), fetchJson("/dashboard")]); state.capabilities = capabilities; state.dashboard = dashboard; renderDashboard(); if (capabilities.features.live_demo) $("#live-tab").classList.remove("hidden"); const samples = await fetchJson("/static-samples"); state.staticSamples = samples.samples || []; renderStaticOptions(); } catch (e) { setError("#static-error", friendlyError(e)); } }
  bootstrap();
})();
